categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Blog
archive_b: Blog: %s
page: Page %d
recent_posts: Recent Posts